//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanya
    {
        public int KId { get; set; }
        public int K2Id { get; set; }
        public int FId { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public int Eski_Fiyat { get; set; }
        public int Yeni_Fiyat { get; set; }
        public byte[] resim { get; set; }
        public int Yuzde { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Kategori_2 Kategori_2 { get; set; }
        public object Kategori_1 { get; internal set; }
    }
}
