//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori_2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategori_2()
        {
            this.Kampanya = new HashSet<Kampanya>();
        }

       
        public int K1Id { get; set; }
        public int K2Id { get; set; }
        public string K2Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kampanya> Kampanya { get; set; }
        public virtual Kategori_1 Kategori_1 { get; set; }
    }
}
